blank_issues_enabled: false
contact_links:
  - name: "Support Question"
    url: "https://github.com/orgs/phpDocumentor/discussions"
    about: "We use GitHub issues only to discuss about bugs and new features. For this kind of questions about using the project, please use the discussions."
