services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  _instanceof:
    phpDocumentor\Guides\Formats\OutputFormat:
      tags: ['phpdoc.guides.format']

  phpDocumentor\Guides\:
    resource: '../src/*'

  phpDocumentor\Guides\References\:
    resource: '../src/References/*'
    exclude:
      - '../src/References/{Resolver,ResolvedReference}.php'
    tags: [ { name: 'phpdoc.guides.reference' } ]

  phpDocumentor\Guides\Formats\OutputFormats:
    arguments:
      $outputFormats: !tagged_iterator phpdoc.guides.format
