name: "Backport"

on: # yamllint disable-line rule:truthy
  pull_request_target:
    types: ["labeled", "closed"]

jobs:
  backport:
    name: "Backport PR"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Backport Action"
        uses: "sorenlouv/backport-github-action@v9.3.1"
        if: "${{ github.event.pull_request.merged == true }}"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          auto_backport_label_prefix: "auto-backport-to-"

      - name: "Info log"
        if: "${{ success() }}"
        run: "cat /home/runner/.backport/backport.info.log"

      - name: "Debug log"
        if: "${{ failure() }}"
        run: "cat /home/runner/.backport/backport.debug.log"
