name: "Sub-split Publishing"

on: # yamllint disable-line rule:truthy
  create:
    tags:
      - "*"
  delete:
    tags:
      - "*"
  push:
    paths:
      - "packages/**/*"
    branches:
      - "main"

jobs:
  publish_sub_splits:
    runs-on: "ubuntu-latest"
    name: "Publish Sub-split"
    steps:
      - uses: "actions/checkout@v3.1.0"
        with:
          fetch-depth: "0"
          persist-credentials: "false"
      - uses: "frankdejonge/use-github-token@1.0.2"
        with:
          authentication: "phpdoc-bot:${{ secrets.BOT_TOKEN }}"
      - name: "Cache splitsh-lite"
        id: "splitsh-cache"
        uses: "actions/cache@v3.2.1"
        with:
          path: "./.splitsh"
          key: "${{ runner.os }}-splitsh-d-101"
      - uses: "frankdejonge/use-subsplit-publish@1.0.0-beta.6"
        with:
          source-branch: "main"
          config-path: "./config.subsplit-publish.json"
          splitsh-path: "./.splitsh/splitsh-lite"
          splitsh-version: "v1.0.1"
